version: 2.1

defaults: &defaults
  docker:
    - image: circleci/node
  working_directory: ~/repo

commands:
  setup-repo:
    steps:
      - checkout
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: yarn install --frozen-lockfile
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache

jobs:
  validate:
    <<: *defaults
    steps:
      - setup-repo
      - run: yarn validate
  release:
    <<: *defaults
    steps:
      - setup-repo
      - run: yarn semantic-release

workflows:
  version: 2
  validate_and_release:
    jobs:
      - validate
      - release:
          requires:
            - validate
